### ISSUE TITLE
不能运行npm run build:wasi

### ISSUE THREAD

**Issue by Roxannej** [alibaba/font-toolkit#12]
clone项目，想本地运行，发现无法启动
<img width="938" alt="截屏2022-12-25 20 24 27" src="https://user-images.githubusercontent.com/52034179/209467806-887eb00b-c8b7-4eae-940f-6475d92aea78.png">

**Comment by Roxannej** [comment]
怀疑是不是rust的版本问题，还是rust的依赖的问题

**Comment by zimond** [comment]
assert is a built-in macro of Rust. It must be something off related to your configuration which is not related to this project. Closing.
